# Generated by Django 5.2.8 on 2025-11-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=20)),
                ('style', models.CharField(max_length=20)),
                ('price', models.IntegerField(max_length=10)),
            ],
        ),
    ]
