# Generated by Django 5.2.8 on 2025-11-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='picture',
            field=models.ImageField(null=True, upload_to='painting_pictures'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='price',
            field=models.IntegerField(),
        ),
    ]
